apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-zdocdtfs
  namespace: default
spec:
  replicas: 4
  selector:
    matchLabels:
      app: deployment-zdocdtfs
  template:
    metadata:
      labels:
        app: deployment-zdocdtfs
    spec:
      containers:
      - image: nginx:1
        name: nginx
