apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-bsadhwtu
  namespace: default
spec:
  replicas: 4
  selector:
    matchLabels:
      app: deployment-bsadhwtu
  template:
    metadata:
      labels:
        app: deployment-bsadhwtu
    spec:
      containers:
      - image: nginx:1
        name: nginx
