apiVersion: batch/v1
kind: Job
metadata:
  name: job-rfnlgplp
  namespace: default
spec:
  backoffLimit: 4
  template:
    spec:
      containers:
      - command:
        - /bin/bash
        - -c
        - echo 'Job executed successfully'
        image: ubuntu:19.04
        name: ubuntu
      restartPolicy: Never
